name: merge-open-assignments.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 2'

jobs:
  merge-assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: pdamianik/merge-prs-with-label-action@15be45147a366dc479b7c74bda2ed45de8072290
        with:
          token: ${{ secrets.PR_MERGE_TOKEN }}
          label: 'assignment'
