name: merge-open-assignments.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 2'

jobs:
  merge-assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: pdamianik/merge-prs-with-label-action@2dff24762b3e808c168b6a9b8c1efa9169c1c5a5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'assignment'
