name: sync-assignments-to-gitlab.yml
on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Add GitLab remote
        run: git remote add gitlab https://12418032:${{ secrets.GITLAB_ACCESS_TOKEN }}@b3.complang.tuwien.ac.at/ep2/2025s/uebung/h12418032.git
      - name: Fetch GitLab remote
        run: git fetch gitlab
      - name: Rebase GitLab remote
        run: git rebase gitlab/main
      - name: compare github to gitlab
        run: git log origin/main..gitlab/main
      - name: compare gitlab to github
        run: git log gitlab/main..origin/main
      - name: Push to GitLab
        run: git push gitlab main
      - name: Remove GitLab remote
        run: git remote remove gitlab
